---
- include_vars: Debian.yml

- name: Install Aptitude
  apt:
    name: aptitude
    state: present
  become: True

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: True

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: ['python-apt', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'wget', 'rsync']
    state: present
    update_cache: yes
  become: True

- name: Add Docker apt signing
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: True

- name: Add Docker stable version apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  become: True

- name: Install Docker and its dependecies
  apt: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
    update_cache: yes
  become: true

- name: Add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: add Kubernetes stable version apt repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
  become: true

- name: Install Kubelet and Kubeadm
  apt:
    name: ['kubelet', 'kubeadm']
    state: present
    update_cache: true
  become: true

- name: Start Kubelet Service
  service:
    name: kubelet
    state: started
    enabled: True
  become: true

- name: Disable swap
  command: swapoff -a
  become: true
  notify:
  - docker-restart