---
- name: "Install kubernetes common packages"
  hosts: all
  gather_facts: false
  pre_tasks:
    #- raw: sudo apt-get -y install python-simplejson
    # action: setup will gather facts after python2 has been installed
    - name: Install required packages to run playbooks
      yum:
        name: ['wget', 'openssl-devel', 'bzip2-devel', 'libffi-devel', 'rsync']
        state: present
      become: True

    - action: setup

  tasks:
  - include_role:
      name: common-packages
    tags:
    - common-tasks

  - meta: flush_handlers

- name: "Install Kubernetest master node"
  hosts: masternodes

  tasks:
  - include_role:
      name: master-node
    tags:
    - kube-master

- name: "Add worker nodes to kubernetes master node"
  hosts: workernodes
  become: yes
  tasks:
  - include_role:
      name:  worker-node
    tags:
      - kube-node