---
- name: "Install kubernetes common packages"
  hosts: all

  tasks:
  - include_role:
      name: common-packages
    tags:
    - common-tasks

  - meta: flush_handlers

- name: "Install Kubernetest master node"
  hosts: masternodes

  tasks:
  - include_role:
      name: master-node
    tags:
    - kube-master

- name: "Add worker nodes to kubernetes master node"
  hosts: workernodes
  become: yes
  tasks:
  - include_role:
      name:  worker-node
    tags:
      - kube-node