---

- name: Create .kube directory  
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  become: True

- name: Copy kube config
  copy:
    src: "{{ playbook_dir }}/config"
    dest: $HOME/.kube/
  become: True

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  become: True

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
  become: True

- name: join cluster
  shell: "{{ join_command_raw.stdout }}"
  become: True